#!/bin/bash

#PBS -N generic_name
#PBS -l nodes=1:ppn=1,mem=30gb,walltime=4:00:00
#PBS -m n
#PBS -j oe
#PBS -r n

# Designed to run on helix.
# Current Nov 2019

# -m n == do NOT email when done
# -j oe == one logfile for out and err
# -r n == not re-runnable
module load R/3.6.0
module unload gcc/4.9.2
module load gcc/7.1.0 pandoc/1.13.1
cd $PBS_O_WORKDIR

Rscript -e "rmarkdown::render('filename.Rmd')"

RETCODE=$?
echo "retcode was $RETCODE" >&2
exit $RETCODE